name: Build LSPosed Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build LSPosed Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build LSPosed module APK
        run: ./gradlew assembleRelease

      - name: Upload built APK
        uses: actions/upload-artifact@v3
        with:
          name: CameraSpoofer-APK
          path: app/build/outputs/apk/release/*.apk
